apiVersion: apps/v1
kind: Deployment

metadata:
  name: incident-service
  namespace: iimp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: incident-service

  template:
    metadata:
      labels:
        app: incident-service

    spec:
      containers:
      - name: incident-service
        image: incident-service:v3
        imagePullPolicy: Never

        ports:
        - containerPort: 7000
